### ISSUE TITLE
Strange errors occurred during inference

### ISSUE THREAD

**Issue by gqf126** [ByteDance-Seed/SeedVR#7]
Loading pretrained ckpt from ./ckpts/seedvr2_ema_7b.pth                                                                                                       
Loading info: <All keys matched successfully>                                                                                                                 
DiT trainable parameters: 8,239,607,872                                                                                                                       
2025-06-17 12:50:17,425 [MainThread][common.decorators][INFO] Completed configure_dit_model in 135.817 seconds.                                               
2025-06-17 12:50:17,425 [MainThread][common.decorators][INFO] Entering configure_vae_model                                                                    
/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is depr
ecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be remove
d in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.                                          
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)                                                                                         
2025-06-17 12:50:17.957417: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to float
ing-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.                       
2025-06-17 12:50:17.990382: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in perf
ormance-critical operations.                                                                                                                                  
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.  
2025-06-17 12:50:19.875329: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT                                   
slicing_up_num: 0                                                                                                                                             
2025-06-17 12:50:29,849 [MainThread][common.decorators][INFO] Completed configure_vae_model in 12.424 seconds.                                                
Total prompts to be generated: 1                                                                                                                              
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 97.40it/s]
0it [00:00, ?it/s]/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torchvision/io/video.py:161: UserWarning: The pts_unit 'pts' gives wrong results. P
lease use pts_unit 'sec'.                                                                                                                                     
  warnings.warn("The pts_unit 'pts' gives wrong results. Please use pts_unit 'sec'.")                                                                         
Read video size: torch.Size([101, 3, 960, 540])                                                                                                               
Encoding videos: [torch.Size([3, 101, 1280, 720])]                                                                                                            
/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/conv.py:605: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION
_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:
919.)                                                                                                                                                         
  return F.conv3d(                                                                                                                                            
Generating with noise shape: torch.Size([26, 160, 90, 16]).                                              
Timestep shifting from 0.0 to tensor([0.], device='cuda:0').  

0617 12:51:11.199000 140509054621504 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -8) local_rank: 0 (pid: 436) of binary: /root/ana
conda3/envs/seedvr/bin/python3.10                                                                                                                            
Traceback (most recent call last):                                                                                                                           
  File "/root/anaconda3/envs/seedvr/bin/torchrun", line 8, in <module>                                   
    sys.exit(main())                                                                                                                                         
  File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)                                                                                                                                
  File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)                                                                                                                                                
  File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run                                                 
    elastic_launch(                                                                                                                                          
  File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__                                    
    return launch_agent(self._config, self._entrypoint, list(args))                                                                                          
  File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent                                
    raise ChildFailedError(                                                                                                                                   
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:                                                                                           
===================================================                                                                                                           
projects/inference_seedvr2_7b.py FAILED                                                                                                                       
---------------------------------------------------                                                                                                          
Failures:                                                                                                                                                     
  <NO_OTHER_FAILURES>                                                                                                                                        
---------------------------------------------------                                                                                                          
Root Cause (first observed failure):                                                                                                                         
[0]:                                                                                                                                                         
  time      : 2025-06-17_12:51:11                                                                             
  host      : VM-63-196-tencentos                                                                                                                            
  rank      : 0 (local_rank: 0)                                                                                                                               
  exitcode  : -8 (pid: 436)
  error_file: <N/A>
  traceback : Signal 8 (SIGFPE) received by PID 436
===================================================

**Comment by yiyunchen** [comment]
I have the same problem, did you solve it?

**Comment by IceClear** [comment]
Hi, thanks for your interest of our work. We notice that similar errors may occur on some special GPUs, e.g., H20. May I know what GPU you are using?

**Comment by gqf126** [comment]
> Hi, thanks for your interest of our work. We notice that similar errors may occur on some special GPUs, e.g., H20. May I know what GPU you are using?

We use H20 for testing. Is there any solution for these devices?

**Comment by kelisiya** [comment]
I also encountered errors during the installation according to the specified version on an 80G A100 GPU with CUDA 12.6.


Read video size: torch.Size([113, 3, 720, 1248])
Encoding videos: [torch.Size([3, 113, 720, 1264])]
Generating with noise shape: torch.Size([29, 90, 158, 16]).
Timestep shifting from 0.0 to tensor([0.], device='cuda:0').
0it [00:18, ?it/s]
[rank0]: Traceback (most recent call last):                                                   | 0/1 [00:00<?, ?it/s]
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/common/cache.py", line 32, in __call__
[rank0]:     result = self.cache[key]
[rank0]: KeyError: 'emb_repeat_0_vid'

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/projects/inference_seedvr2_3b.py", line 330, in <module>
[rank0]:     generation_loop(runner, **vars(args))
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/projects/inference_seedvr2_3b.py", line 278, in generation_loop
[rank0]:     samples = generation_step(runner, text_embeds, cond_latents=cond_latents)
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/projects/inference_seedvr2_3b.py", line 124, in generation_step
[rank0]:     video_tensors = runner.inference(
[rank0]:   File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/projects/video_diffusion_sr/infer.py", line 326, in inference
[rank0]:     latents = self.sampler.sample(
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/common/diffusion/samplers/euler.py", line 54, in sample
[rank0]:     pred = f(SamplerModelArgs(x, t, i))
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/projects/video_diffusion_sr/infer.py", line 328, in <lambda>
[rank0]:     f=lambda args: classifier_free_guidance_dispatcher(
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/common/diffusion/utils.py", line 76, in classifier_free_guidance_dispatcher
[rank0]:     return pos()
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/projects/video_diffusion_sr/infer.py", line 329, in <lambda>
[rank0]:     pos=lambda: self.dit(
[rank0]:   File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/nadit.py", line 220, in forward
[rank0]:     vid, txt, vid_shape, txt_shape = gradient_checkpointing(
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/nadit.py", line 32, in gradient_checkpointing
[rank0]:     return module(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/nablocks/mmsr_block.py", line 108, in forward
[rank0]:     vid_attn, txt_attn = self.ada(vid_attn, txt_attn, layer="attn", mode="in", **ada_kwargs)
[rank0]:   File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/mm.py", line 70, in forward
[rank0]:     vid = vid_module(vid, *get_args("vid", args), **get_kwargs("vid", kwargs))
[rank0]:   File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/modulation.py", line 80, in forward
[rank0]:     emb = cache(
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/common/cache.py", line 34, in __call__
[rank0]:     result = fn()
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/modulation.py", line 83, in <lambda>
[rank0]:     torch.cat([e.repeat(l, *([1] * e.ndim)) for e, l in zip(emb, hid_len)]),
[rank0]:   File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/modulation.py", line 83, in <listcomp>
[rank0]:     torch.cat([e.repeat(l, *([1] * e.ndim)) for e, l in zip(emb, hid_len)]),
[rank0]: RuntimeError: CUDA error: no kernel image is available for execution on the device
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by Taooooozi** [comment]
> I also encountered errors during the installation according to the specified version on an 80G A100 GPU with CUDA 12.6.
> 
> `CUDA_VISIBLE_DEVICES=1 torchrun --nproc-per-node=1 projects/inference_seedvr2_3b.py --video_path /data3/home/jxie/experiment/SeedVR/testset/ --output_dir /data3/home/jxie/experiment/SeedVR/output --seed 666 --res_h 720 --res_w 1280 --sp_size 1 `
> 
> Read video size: torch.Size([113, 3, 720, 1248]) Encoding videos: [torch.Size([3, 113, 720, 1264])] Generating with noise shape: torch.Size([29, 90, 158, 16]). Timestep shifting from 0.0 to tensor([0.], device='cuda:0'). 0it [00:18, ?it/s] [rank0]: Traceback (most recent call last): | 0/1 [00:00<?, ?it/s] [rank0]: File "/data3/home/jxie/experiment/SeedVR/common/cache.py", line 32, in **call** [rank0]: result = self.cache[key] [rank0]: KeyError: 'emb_repeat_0_vid'
> 
> [rank0]: During handling of the above exception, another exception occurred:
> 
> [rank0]: Traceback (most recent call last): [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/inference_seedvr2_3b.py", line 330, in [rank0]: generation_loop(runner, **vars(args)) [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/inference_seedvr2_3b.py", line 278, in generation_loop [rank0]: samples = generation_step(runner, text_embeds, cond_latents=cond_latents) [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/inference_seedvr2_3b.py", line 124, in generation_step [rank0]: video_tensors = runner.inference( [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context [rank0]: return func(*args, **kwargs) [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/video_diffusion_sr/infer.py", line 326, in inference [rank0]: latents = self.sampler.sample( [rank0]: File "/data3/home/jxie/experiment/SeedVR/common/diffusion/samplers/euler.py", line 54, in sample [rank0]: pred = f(SamplerModelArgs(x, t, i)) [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/video_diffusion_sr/infer.py", line 328, in [rank0]: f=lambda args: classifier_free_guidance_dispatcher( [rank0]: File "/data3/home/jxie/experiment/SeedVR/common/diffusion/utils.py", line 76, in classifier_free_guidance_dispatcher [rank0]: return pos() [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/video_diffusion_sr/infer.py", line 329, in [rank0]: pos=lambda: self.dit( [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/nadit.py", line 220, in forward [rank0]: vid, txt, vid_shape, txt_shape = gradient_checkpointing( [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/nadit.py", line 32, in gradient_checkpointing [rank0]: return module(*args, **kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/nablocks/mmsr_block.py", line 108, in forward [rank0]: vid_attn, txt_attn = self.ada(vid_attn, txt_attn, layer="attn", mode="in", **ada_kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/mm.py", line 70, in forward [rank0]: vid = vid_module(vid, *get_args("vid", args), **get_kwargs("vid", kwargs)) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/modulation.py", line 80, in forward [rank0]: emb = cache( [rank0]: File "/data3/home/jxie/experiment/SeedVR/common/cache.py", line 34, in **call** [rank0]: result = fn() [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/modulation.py", line 83, in [rank0]: torch.cat([e.repeat(l, *([1] * e.ndim)) for e, l in zip(emb, hid_len)]), [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/modulation.py", line 83, in [rank0]: torch.cat([e.repeat(l, *([1] * e.ndim)) for e, l in zip(emb, hid_len)]), [rank0]: RuntimeError: CUDA error: no kernel image is available for execution on the device [rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. [rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1. [rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I have the same problem, did you solve it?

**Comment by xduzhangjiayu** [comment]
> I also encountered errors during the installation according to the specified version on an 80G A100 GPU with CUDA 12.6.
> 
> `CUDA_VISIBLE_DEVICES=1 torchrun --nproc-per-node=1 projects/inference_seedvr2_3b.py --video_path /data3/home/jxie/experiment/SeedVR/testset/ --output_dir /data3/home/jxie/experiment/SeedVR/output --seed 666 --res_h 720 --res_w 1280 --sp_size 1 `
> 
> Read video size: torch.Size([113, 3, 720, 1248]) Encoding videos: [torch.Size([3, 113, 720, 1264])] Generating with noise shape: torch.Size([29, 90, 158, 16]). Timestep shifting from 0.0 to tensor([0.], device='cuda:0'). 0it [00:18, ?it/s] [rank0]: Traceback (most recent call last): | 0/1 [00:00<?, ?it/s] [rank0]: File "/data3/home/jxie/experiment/SeedVR/common/cache.py", line 32, in **call** [rank0]: result = self.cache[key] [rank0]: KeyError: 'emb_repeat_0_vid'
> 
> [rank0]: During handling of the above exception, another exception occurred:
> 
> [rank0]: Traceback (most recent call last): [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/inference_seedvr2_3b.py", line 330, in [rank0]: generation_loop(runner, **vars(args)) [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/inference_seedvr2_3b.py", line 278, in generation_loop [rank0]: samples = generation_step(runner, text_embeds, cond_latents=cond_latents) [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/inference_seedvr2_3b.py", line 124, in generation_step [rank0]: video_tensors = runner.inference( [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context [rank0]: return func(*args, **kwargs) [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/video_diffusion_sr/infer.py", line 326, in inference [rank0]: latents = self.sampler.sample( [rank0]: File "/data3/home/jxie/experiment/SeedVR/common/diffusion/samplers/euler.py", line 54, in sample [rank0]: pred = f(SamplerModelArgs(x, t, i)) [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/video_diffusion_sr/infer.py", line 328, in [rank0]: f=lambda args: classifier_free_guidance_dispatcher( [rank0]: File "/data3/home/jxie/experiment/SeedVR/common/diffusion/utils.py", line 76, in classifier_free_guidance_dispatcher [rank0]: return pos() [rank0]: File "/data3/home/jxie/experiment/SeedVR/projects/video_diffusion_sr/infer.py", line 329, in [rank0]: pos=lambda: self.dit( [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/nadit.py", line 220, in forward [rank0]: vid, txt, vid_shape, txt_shape = gradient_checkpointing( [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/nadit.py", line 32, in gradient_checkpointing [rank0]: return module(*args, **kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/nablocks/mmsr_block.py", line 108, in forward [rank0]: vid_attn, txt_attn = self.ada(vid_attn, txt_attn, layer="attn", mode="in", **ada_kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/mm.py", line 70, in forward [rank0]: vid = vid_module(vid, *get_args("vid", args), **get_kwargs("vid", kwargs)) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl [rank0]: return self._call_impl(*args, **kwargs) [rank0]: File "/root/anaconda3/envs/seedvr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl [rank0]: return forward_call(*args, **kwargs) [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/modulation.py", line 80, in forward [rank0]: emb = cache( [rank0]: File "/data3/home/jxie/experiment/SeedVR/common/cache.py", line 34, in **call** [rank0]: result = fn() [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/modulation.py", line 83, in [rank0]: torch.cat([e.repeat(l, *([1] * e.ndim)) for e, l in zip(emb, hid_len)]), [rank0]: File "/data3/home/jxie/experiment/SeedVR/models/dit_v2/modulation.py", line 83, in [rank0]: torch.cat([e.repeat(l, *([1] * e.ndim)) for e, l in zip(emb, hid_len)]), [rank0]: RuntimeError: CUDA error: no kernel image is available for execution on the device [rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. [rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1. [rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Same problem, did you solve it?

**Comment by zws98** [comment]
same problem

**Comment by xduzhangjiayu** [comment]
@zws98 @kelisiya Did you solve it? I tried for 2 days but can't solve, I used A100 and have tried cuda 12.8, 12.4, 12.1, and still can't work

**Comment by zhangvia** [comment]
the torch version is important. i got torch 2.6.0+cuda12.4, and install apex from source. no problem here

**Comment by maniraja1122** [comment]
Shift to latest GPUs

**Comment by ccssyyy** [comment]
i solve the problem with pip install nvidia-cublas-cu12 == 12.4.5.8, my device is h20, with torch 2.3.0+cuda 12.1

**Comment by zhuang2002** [comment]
same problem

**Comment by caozhenxiang-kouji** [comment]
It seems that the apex provided by the author doesn't work well for all kinds of environments.
I downloaded the source code from the https://github.com/NVIDIA/apex?tab=readme-ov-file and builded myself. That solved the problem.
